export default Object.freeze({
    INITIALIZE: 'INITIALIZE',

    START_AUTH_FETCHING: 'START_AUTH_FETCHING',
    STOP_AUTH_FETCHING:  'STOP_AUTH_FETCHING',

    START_FEED_FETCHING: 'START_FEED_FETCHING',
    STOP_FEED_FETCHING:  'STOP_FEED_FETCHING',
});
